# Generated by Django 5.0.6 on 2025-02-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0, help_text='Kilometers driven'),
        ),
    ]
